name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 366707332722.dkr.ecr.us-east-2.amazonaws.com/order-api

      - name: Build and Push Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t 366707332722.dkr.ecr.us-east-2.amazonaws.com/order-api:$IMAGE_TAG .
          docker push 366707332722.dkr.ecr.us-east-2.amazonaws.com/order-api:$IMAGE_TAG

      - name: Deploy to ECS
        run: |
          echo "Update ECS service here (manual or script)"
